input_data = {
    'received_at': '2021-01-01 12:00:00',
    'date': '2021-01-01',
    'time': '12:00:00',
    'purchase_order': 'PO-1234',
    'discount': '0.00',
    'notes': 'Notes',
    'table_of_items_ordered': 'SKU: FD0101, QTY: 1, Price: 167.97, TURN5,\nSKU: DD1001, QTY: 1, Price: 83.97, TURN5,\nSKU: EK5012, QTY: 1, TURN5,',
    'billing_customer_name': 'Bill Customer',
    'billing_address_line1': '123 Main St.',
    'billing_address_line2': '\"\"',
    'billing_address_city': 'Anytown',
    'billing_address_state_or_province': 'CA',
    'billing_address_postal_code': '12345',
    'billing_address_country': 'USA',
    'billing_address_email_address': 'bill@email.com',
    'billing_address_phone': '000000000000',
    'shipping_customer_name': 'Ship Customer',
    'shipping_address_line1': '123 Main St.',
    'shipping_address_line2': '',
    'shipping_address_city': 'Anytown',
    'shipping_address_state_or_province': 'CA',
    'shipping_address_postal_code': '12345',
    'shipping_address_country': 'USA',
    'shipping_address_email_address': 'ship@email.com',
    'shipping_address_phone': '000000000000',
    'tax':  '0.00'
}
